### PR TITLE
To-do List Project - JavaScript

### PR DESCRIPTION
**Pull request by rloterh**
This project consists of a single page fully built with JavaScript, with three different modules/views displaying a My Lists/General List section, a My Tasks section, and a Task details section. Webpack was used for bundling the different modules.
- User can create/edit/delete a project (left column)
- User can select a specific project to see its tasks (middle column)
- User can create/edit/delete a task (middle column)
- User can select a task to see its details (right column)

Built With:
- JavaScript
- Webpack
- HTML / CSS
- Git

### CODE REVIEW

**Review by oloomoses — COMMENTED** [review]
# Invalid
I cannot review this project because it does not have a descriptive readme. Kindly write a descriptive readme and ask for another review.

_Slack: Oloo Moses_

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @rloterh and @Milypm   ! :wave: :wave:

#### You have done well so far :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.


**Recommended**
- [x] Don't commit unnecessary large files to Github, add them to the `.gitignore` file.
- [x] To-do item / Task ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/todo_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))
 - It has a title
 - It has a description
Currently, there's only the description. Kindly add a title property.
 
 __Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by rloterh** [comment]
Added title to task

**Review by oloomoses — CHANGES_REQUESTED** [review]
**Hello team,** 
You have really done a great job on this project
### Highlights
- Well done on the styling :muscle: 
- Great job on the readme and the pull request :clap: 

### To improve
- [x] Kindly add the .vscode and node_modules folder in .gitignore and ensure that they are not included in the project repo since they are not part of the project files.
- [x] I am not able to add tasks to other lists created other than the default list. Kindly ensure that the lists are clickable and tasks can be added under them ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/projects_requirement.png) From Odin).

Kindly implement the above changes and ask for another review.
**Feel free to reach me on slack or leave a comment while mentioning me and I will be happy to respond**

_Slack: Oloo Moses_

**Comment by Milypm** [comment]
Requested changes from this PR were implemented and applied from a different branch (build) and a new PR was created for the next code reviews.

**Pull request closed without merging**
